version: '2'
services:
    web:
        build: .
        volumes:
            - ./:/var/www/app/
        ports:
            - 80:8888
            - 35729:35729
        command: bash -c "npm install && npm start"
